import { useQuery } from "@apollo/client";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { GET_PRODUCT_BY_CATEGORY } from "./schema";

const CategoryId = () => {
    const router = useRouter()
    const { unique } = router.query

    const { loading, data, error } = useQuery(GET_PRODUCT_BY_CATEGORY, {
        variables: {
            categoryId: unique
        }
    })

    if (loading) return <p>Loading ...</p>;
    if (error) return `Error! ${error}`;

    console.log(data)

    return (
        <div className="{styles.main}">
            <Head>
                <title>Detail Category page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Link href={'/'}><p>Back to Home</p></Link>
                <h1 style={{ textAlign: 'center' }}>Detail Category Page</h1>
                <p> Name : {data.category.name}</p>
            </div>
        </div>
    )
}

export default CategoryId