import { gql, useQuery } from '@apollo/client'
import Link from 'next/link'
import styles from '@styles/Home.module.css'
import Head from 'next/head'

const GET_CATEGORIES = gql`
    {
        categories(filters:{}) {
            items {
                name
                id
            }
        }
    }
`

const Categories = () => {
    const title = "category"
    const response = useQuery(GET_CATEGORIES)

    const { data, loading, error } = response
    if (loading) return 'Loading....'
    if (error) return `Error: ${error.message}`

    console.log(data)

    return (
        <div>
            <Head>
                <title>Use Query page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Link href={'/'}><p>Back to Home</p></Link>
            <h1 style={{ textAlign: 'center' }}>Use Query Page</h1>
            <div>
                {data?.categories && data.categories.items.map((item) => (
                    <ul>
                        <li>
                            <Link href={`/categories/${item.id}`} key={item.id}>
                                {item.name}
                            </Link>
                            {/* <Image width= {400} height={400} src={} alt={} /> */}
                        </li>
                    </ul>
                ))
                }
            </div>
        </div>
    )
}

export default Categories