import { GET_CATEGORIES } from "./schema";
import { styles } from '@styles/Home.module.css'
import { useLazyQuery } from "@apollo/client";
import Head from "next/head";
import Link from "next/link";

const Lazy = () => {
    const [getCategory, { loading, error, data }] = useLazyQuery(GET_CATEGORIES);

    if (loading) return <p>Loading ...</p>;
    if (error) return `Error! ${error}`;

    return (
        <div className="{styles.main}">
            <Head>
                <title>Lazy Query page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Link href={'/'}><p>Back to Home</p></Link>
                <h1 style={{ textAlign: 'center' }}>Lazy Query Page</h1>
                <button onClick={() => getCategory()}>
                    Click to get Category
                </button>
                {data?.categories && data.categories.items.map((item) => (
                    <ul>
                        <li>
                            <Link href={`/categories/${item.id}`} key={item.id}>
                                {item.name}
                            </Link>
                        </li>
                    </ul>
                ))
                }
            </div>
        </div>
    );
}

export default Lazy