import { data } from './data'
import Link from 'next/dist/client/link'
import Image from 'next/image'
import styles from '../../styles/Border.module.css'
import Head from 'next/head'

const news = () => {
    console.log(data)
    return (
        <div>
            <Head>
                <title>News page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className={styles.color}>Ini halaman news (colored with module css)</h1>
            {data && data.map((item) => (
                <ul key={item.id}>
                    <Link href={{
                        pathname: `news/${item.url}`,
                        query: {
                            title: item.title,
                            content: item.content,
                            image: item.image
                        }
                    }} as={`news/${item.url}`}>
                        <li>
                            {item.title} (colored with jsx)
                        </li>
                    </Link>
                    <Image
                        alt='Bunga'
                        src={item.image}
                        width={700}
                        height={450}
                    />
                </ul>
            ))}
            <style jsx>
                {
                    `
                    li {
                        color: yellow
                    }
                    `
                }
            </style>
        </div>
    )
}

export default news