import { Html, Head, NextScript, Main } from "next/document";

export default function Document() {
    return (
        <Html>
            <Head>
                <title>Document</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}