import Head from "next/head"

const about = () => {
    return (
        <div>
            <Head>
                <title>About page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h3>Ini halaman about</h3>
        </div>
    )
}

export default about